services:
  - type: web
    name: rctv
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn rctv.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
      - key: DEBUG
        value: "False"
      - key: RC_ACCESS_TOKEN
        sync: false
